language: ruby
sudo: false
cache: bundler
script: 'bundle exec rake test:coverage --trace'
rvm:
  - 2.2
  - 2.3
  - jruby-9000
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-9000
